root: true

plugins:
  - babel
  - prettier

env:
  node: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'prettier'

rules:
  prettier/prettier: 0
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0
