plugins:
  - babel
  - jest
  
env:
  node: true
  browser: true
  jest: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parser: babel-eslint

rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: ['error', { 'props': false }]
