plugins:
  - babel

env:
  node: true
  browser: true

extends:
  - 'airbnb-base'

parser: babel-eslint

rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: ['error', { 'props': false }]
